
--Q1. What is the total revenue generated by male vs. female customers?

select gender, sum(purchase_amount) as total_revenue
from customer
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id, discount_applied, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased, round(avg(review_rating::numeric),2) as avg_rating
from customer
group by item_purchased
order by avg_rating desc
limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select shipping_type, round(avg(purchase_amount),2) as avg_purchase_amount
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select subscription_status,
count(customer_id) as total_customer,
round(avg(purchase_amount),2) as avg_spend,
sum(purchase_amount) as total_revenue
from customer
group by subscription_status

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,
	round(100.0 * sum(case when discount_applied ='Yes' Then 1 ELSE 0 END)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with item_count as(
select customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 then 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
	from customer
)
select customer_segment, count(customer_id) as customer, sum(previous_purchases) as prev_purchase
FROM item_count
group by customer_segment
order by prev_purchase desc;

--Q8. What are the top 3 most purchased products within each category?

select * from customer
with purchase_product as(
select category, item_purchased,count(customer_id) as customer,
row_number() over(partition by category order by count(customer_id)) as item_rank
from customer
group by category, item_purchased
)
select category, item_purchased,item_rank
from purchase_product
where item_rank <=3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status, count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group?

select * from customer
select age_group, sum(purchase_amount) as revenue_contribution
from customer
group by age_group
order by revenue_contribution desc;
	



















	



















	
	
	
)























